import { getAiConfig } from './config.js'; import { createVisionProvider } from './providers/index.js';
import { normalizePosterAnalysis, stripJsonFence } from './normalize.js'; import { validatePosterAnalysis } from './schema.js'; import { AiError } from './errors.js'; import { getCache, makeCacheKey, setCache } from './cache.js';
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function parseProviderData(data:unknown):unknown{ if(typeof data==='object'&&data!==null)return data; if(typeof data!=='string')throw new AiError('AI_INVALID_OUTPUT','AI 返回内容为空。',422,false); try{return JSON.parse(stripJsonFence(data));}catch{throw new AiError('AI_INVALID_OUTPUT','AI 返回了无法解析的 JSON。',422,false,data);} }
export async function analyzePoster(imageBase64:string,mimeType:string,outerSignal?:AbortSignal){
  const cfg=getAiConfig(); const clean=imageBase64.includes(',')?imageBase64.slice(imageBase64.indexOf(',')+1):imageBase64; const key=makeCacheKey(clean,cfg); const hit=getCache(key); if(hit)return {data:hit.data,meta:{...hit,cached:true,promptVersion:cfg.promptVersion,schemaVersion:cfg.schemaVersion}};
  const provider=createVisionProvider(cfg); const total=new AbortController(); const relay=()=>total.abort(outerSignal?.reason); outerSignal?.addEventListener('abort',relay,{once:true}); const timer=setTimeout(()=>total.abort(new Error('total deadline')),cfg.totalDeadlineMs); const started=Date.now(); let last:any;
  try{for(let attempt=0;attempt<=cfg.maxRetries;attempt++){try{const r=await provider.analyzePoster({imageBase64:clean,mimeType,signal:total.signal}); const normalized=normalizePosterAnalysis(parseProviderData(r.data)); const v=validatePosterAnalysis(normalized); if(v.ok === false) throw new AiError('AI_INVALID_OUTPUT', `AI 输出未通过校验：${v.errors.join('; ')}`, 422, false); const entry={data:v.data,createdAt:new Date().toISOString(),provider:r.provider,model:r.model,latencyMs:Date.now()-started,usage:r.usage}; setCache(key,entry); return {data:v.data,meta:{...entry,cached:false,promptVersion:cfg.promptVersion,schemaVersion:cfg.schemaVersion,requestId:r.requestId}};}catch(e:any){last=e;if(attempt>=cfg.maxRetries||!e?.retryable)throw e;await sleep(650+Math.floor(Math.random()*300));}} throw last;}finally{clearTimeout(timer);outerSignal?.removeEventListener('abort',relay);}
}
